### ISSUE TITLE
How to measure audio similarity ?

### ISSUE THREAD

**Issue by yogendra-yatnalkar** [Aaron-AALG/SpectroMap#1]
Hi, thanks for the awesome repository. I am very new to the audio processing and analysis domain. I have 2 audio files of equal length and same properties. My task is the measure if these 2 audio files are nearly identical or not. 

In the given repo, let's say if I compute two spectromaps for the 2 audio files, how do I define similarity between 2 spectromaps ? Can anyone please guide me on this front ?

Thanks in advance.

**Comment by Aaron-AALG** [comment]
Hi, Yogendra Yatnalkar,

As far as signal analysis is concerned, multiple alternatives exist for measuring similarities between audio excerpts. Then, it is not an easy task to determine a single manner for attaching such a problem. In my [last work](https://link.springer.com/chapter/10.1007/978-3-031-07015-0_16), we propose a measure of musical similarity between fragments of digital audio using a clustering process based on fuzzy logic [(B. Martinez, 2019)](https://doi.org/10.1007/978-3-030-21392-3_19). You can find more information here as well [(B. Martinez, 2017)](https://doi.org/10.1007/978-3-319-71827-9_21). The motivation for using SpectroMap is the extraction of fingerprints of a list with audio files to handle a larger amount of data efficiently.

I hope this answer can help you.
Greetings,
Aarón.

**Comment by yogendra-yatnalkar** [comment]
Hi @Aaron-AALG thanks a lot for your response. Sorry, I completely missed closing this issue as I got diverted from this work. I will have a look at the resources pointed by you for my own understanding. Thanks again.
